name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Format
        if: ${{ hashFiles('Cargo.toml') != '' }}
        run: cargo fmt --check
      - name: Clippy
        if: ${{ hashFiles('Cargo.toml') != '' }}
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test
        if: ${{ hashFiles('Cargo.toml') != '' }}
        run: cargo test --all
